'use client';
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { Phone, PhoneOff, Mic, MicOff, X } from 'lucide-react-native';
import { useCall } from '@/context/CallContext';

export default function CallOverlay() {
  const { callState, peerName, formattedTime, isMuted, endedMessage, answerCall, declineCall, endCall, toggleMute } = useCall();
  if (callState === 'idle') return null;
  if (callState === 'ringing') return <View style={styles.incoming}><View style={styles.card}><View style={styles.avatar}><Phone color="#fff" size={30} /></View><Text style={styles.name}>{peerName}</Text><Text style={styles.subtitle}>is calling you</Text><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel="Decline call" style={[styles.action, styles.decline]} onPress={declineCall}><PhoneOff color="#fff" size={22} /><Text style={styles.actionLabel}>Decline</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Answer call" style={[styles.action, styles.answer]} onPress={answerCall}><Phone color="#fff" size={22} /><Text style={styles.actionLabel}>Answer</Text></Pressable></View></View></View>;
  if (callState === 'ended') return <View pointerEvents="none" style={styles.toast}><Text style={styles.toastText}>{endedMessage}</Text></View>;
  const active = callState === 'in-call';
  return <View style={styles.pill}><View style={styles.pillText}><Text style={styles.pillTitle}>{active ? `${peerName} · ${formattedTime}` : `Calling ${peerName}…`}</Text>{active && <Text style={styles.pillStatus}>Voice call</Text>}</View>{active && <Pressable accessibilityRole="button" accessibilityLabel={isMuted ? 'Unmute microphone' : 'Mute microphone'} onPress={toggleMute} style={styles.iconButton}>{isMuted ? <MicOff color="#17201a" size={18} /> : <Mic color="#17201a" size={18} />}</Pressable>}<Pressable accessibilityRole="button" accessibilityLabel={active ? 'End call' : 'Cancel call'} onPress={() => endCall()} style={styles.endButton}>{active ? <><PhoneOff color="#fff" size={18} /><Text style={styles.endLabel}>End call</Text></> : <><X color="#fff" size={18} /><Text style={styles.endLabel}>Cancel</Text></>}</Pressable></View>;
}
const styles = StyleSheet.create({ incoming: { ...StyleSheet.absoluteFillObject, zIndex: 20000, backgroundColor: 'rgba(8,15,12,.72)', alignItems: 'center', justifyContent: 'center', padding: 24 }, card: { width: '100%', maxWidth: 360, borderRadius: 28, backgroundColor: '#fff', alignItems: 'center', padding: 32 }, avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#16a34a', alignItems: 'center', justifyContent: 'center', marginBottom: 18 }, name: { fontSize: 24, fontWeight: '700', color: '#142018' }, subtitle: { marginTop: 6, color: '#657268', fontSize: 16 }, actions: { flexDirection: 'row', gap: 44, marginTop: 30 }, action: { width: 82, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center', gap: 3 }, actionLabel: { color: '#fff', fontSize: 12, fontWeight: '600' }, endLabel: { color: '#fff', fontSize: 12, fontWeight: '600' }, decline: { backgroundColor: '#dc2626' }, answer: { backgroundColor: '#16a34a' }, pill: { position: 'absolute', top: 50, alignSelf: 'center', zIndex: 10000, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 28, backgroundColor: '#fff', paddingLeft: 18, paddingVertical: 8, paddingRight: 8, shadowColor: '#000', shadowOpacity: .18, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 12 }, pillText: { minWidth: 120 }, pillTitle: { color: '#17201a', fontWeight: '700', fontSize: 14 }, pillStatus: { color: '#6b766d', fontSize: 11, marginTop: 2 }, iconButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#e9f7ed', alignItems: 'center', justifyContent: 'center' }, endButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#dc2626', alignItems: 'center', justifyContent: 'center' }, toast: { position: 'absolute', top: 60, alignSelf: 'center', zIndex: 10000, backgroundColor: '#18211b', borderRadius: 20, paddingHorizontal: 20, paddingVertical: 12 }, toastText: { color: '#fff', fontWeight: '600' } });
